<a href="https://colab.research.google.com/github/CarlosOrte/Descriptive-and-Predictive-Analytics-Code/blob/main/Practica4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Práctica 4. Manipulación de matrices**

Maestría en Inteligencia artificial y analítica de datos

Programación para analítica descriptiva y predictiva

Matrícula: 266231




Creamos dos matrices 3x3 con numeros aleatorios entre 1 y **10**

In [2]:
import numpy as np

# Crear dos matrices 3x3 con valores aleatorios entre 1 y 10
matriz1 = np.random.randint(1, 11, (3, 3))
matriz2 = np.random.randint(1, 11, (3, 3))

print("Matriz 1:")
print(matriz1)

print("\nMatriz 2:")
print(matriz2)

Matriz 1:
[[ 2  1  6]
 [ 4  8  5]
 [ 5 10  5]]

Matriz 2:
[[10  4  7]
 [ 8  1  1]
 [ 5  2  8]]


**1. Suma de matrices**

In [3]:
suma = matriz1 + matriz2
print("\nSuma de las matrices:")
print(suma)


Suma de las matrices:
[[12  5 13]
 [12  9  6]
 [10 12 13]]


**2. Resta de la segunda matriz a la primera**

In [4]:
resta = matriz1 - matriz2
print("\nResta (Matriz 1 - Matriz 2):")
print(resta)


Resta (Matriz 1 - Matriz 2):
[[-8 -3 -1]
 [-4  7  4]
 [ 0  8 -3]]


**3. Multiplicar la primera matriz por 2**

In [5]:
multiplicacion_escalar = matriz1 * 2
print("\nMatriz 1 multiplicada por 2:")
print(multiplicacion_escalar)


Matriz 1 multiplicada por 2:
[[ 4  2 12]
 [ 8 16 10]
 [10 20 10]]


**4. Multiplicación matricial**

In [6]:
multiplicacion_matricial = np.dot(matriz1, matriz2)
print("\nMultiplicación matricial (Matriz 1 x Matriz 2):")
print(multiplicacion_matricial)


Multiplicación matricial (Matriz 1 x Matriz 2):
[[ 58  21  63]
 [129  34  76]
 [155  40  85]]
